#
###################################
# Site wide configuration
####################################
#
title: My Personal Website
email: carrie07@connect.hku.hk
description: carrie's blog,powered by jekyll.
url: https://carrieww.github.io # the base hostname & protocol for your site
keywords: ["jekyll", "java", "scala","blog"]
github_repo: "https://github.com/carrieww/carrieww.github.io.git"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: WANG Yun - Carrie
  avatar: Photo_WangYun.jpg
  job: "Java & Scala Developer"
  bio: "Senior student major in Decision Analytics and Mathematics at the University of Hong Kong."
  email: carrie07@connect.hku.hk
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: carrieww #username
#   stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
